### ISSUE TITLE
Unexpected names of global scope functions

### ISSUE THREAD

**Issue by mudrd8mz** [wset/moodle-filter_cloudfront_signurl#2]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

Your lib.php defines functions like rsa_sha1_sign(), url_safe_base64_encode() etc. Either all these must have the frankenstyle name prefix, or (maybe better) you may wish to wrap them as static methods of a single helper class. So you would call them like, for example:

```
filter_cloudfront_signurl_helper::rsa_sha1_sign()
```

**Comment by owenbarritt** [comment]
Thanks.  I've updated the code accordingly and will resubmit
